server:  port: 8004spring:  application:    name: springboot-provider    
  datasource:
    username: hydrocarbon
    password: hydrocarbon
#    url: jdbc:mysql://localhost:3306/t_carbon_test?serverTimezone=UTC
    url: jdbc:mysql://47.110.161.228:13006/dc_dongxi_street?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update  aop:    auto: false
    proxy-target-class: false
    eureka:  client: #客户端注册进eureka服务列表内    service-url: #      defaultZone: http://localhost:7001/eureka       defaultZone: http://eureka7001.com:7001/eureka/#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/        instance:    instance-id: springboot-provider8004 #自定义服务名称信息    prefer-ip-address: true     #访问路径可以显示IP地址      info:   app.name: lhb-springcloud  company.name: www.lhb.com  build.artifactId: $project.artifactId$  build.version: $project.version$b    
